---
- name: Konfiguriere APT Debian sources.list
  ansible.builtin.template:
    src: "templates/Debian/sources.list.j2"
    dest: "{{ common__apt_sources_list_file }}"
    owner: root
    group: root
    mode: 0644
  vars:
    sources_list: "{{ common__apt_debian_sources }}"
  when: common__apt_debian_sources is defined
  tags: dist_upgrade

- name: Erstelle APT Konfigurations-Datei
  template:
    src: "{{ ansible_os_family }}/apt-conf.j2"
    dest: "{{ common__apt_conf_folder | dirname }}/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
  vars:
    options: "{{ item.value }}"
  loop: "{{ common__apt_config_options | dict2items }}"

