---
- name: Konfiguriere fail2ban Dateien
  ansible.builtin.template:
    src: "templates/fail2ban-config.j2"
    dest: "{{ common__f2b_folder }}/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
  vars:
    __content: "{{ item.value }}"
  loop_control:
    label: "{{ common__f2b_folder }}/{{ item.key }}"
  loop: "{{ common__f2b_config | dict2items }}"
  notify: restart fail2ban
...
