---
- name: Prüfe hosts-Datei und aktualisiere Hostname
  ansible.builtin.replace:
    path: "{{ common__hosts_file }}"
    regexp: "{{ ansible_hostname }}"
    replace: "{{ common__new_hostname }}"
  register:
    common_hostname_changed
  when:
    common__new_hostname is defined

- name: Prüfe hosts-Datei und aktualisiere Domainname
  ansible.builtin.replace:
    path: "{{ common__hosts_file }}"
    regexp: "{{ ansible_domain }}"
    replace: "{{ common__new_domainname }}"
  register:
    common_domainname_changed
  when:
    common__new_domainname is defined

- name: Aktualisiere Hostname
  ansible.builtin.hostname:
    name: "{{ common__new_hostname }}"
  register:
    common_hostname_changed
  when:
    common__new_hostname is defined

- name: Hinweis für Neustart
  ansible.builtin.debug:
    msg: Bitte den Host oder Domainname anpassen und System neustarten!
  when:
    common_hostname_changed.changed or common_domainname_changed.changed
