---
- name: Include OS family vars
  include_vars:
    "{{ ansible_os_family }}.yaml"

- name: Include OS distribution vars
  include_vars:
    "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yaml"

- include: hostname.yaml
- include: packages.yaml
- include: user.yaml
- include: locales.yaml
- include: time.yaml
- include: unattended_upgrades.yaml
