---
- { include: hostname.yml, become: yes }
- { include: user.yml, become: yes }
- { include: locales.yml, become: yes }
- { include: time.yml, become: yes }
- { include: unattended_upgrades.yml, become: yes }
