---
- name: Setze Zeitzone auf "{{ common__timezone }}"
  community.general.timezone:
    name: "{{ common__timezone }}"
  when: common__timezone is defined

- name: Konfiguriere ntp.conf
  ansible.builtin.template:
    src: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}/\
      ntp.conf.j2"
    dest: "{{ common__ntpconf_file }}"
  notify: restart ntp

- name: Aktiviere und starte den NTP-Service
  ansible.builtin.service:
    name: "{{ common__service_ntp }}"
    state: started
    enabled: true
