---
- name: Konfiguriere unattended-upgrades
  template:
    src: "{{ ansible_os_family }}/auto-upgrades.j2"
    dest: "{{ common__unattended_upgrade_autoupgrades_file }}"
    owner: root
    group: root
    mode: 0644

- name: create unattended-upgrades configuration
  template:
    src: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}/\
      unattended-upgrades.j2"
    dest: "{{ common__unattended_upgrade_upgrades_file }}"
    owner: root
    group: root
    mode: 0644
