---
- name: Konfiguriere unattended-upgrades
  template:
    src: auto-upgrades.j2
    dest: "{{ common__unattended_upgrade_autoupgrades_file }}"
    owner: root
    group: root
    mode: 0644

- name: create unattended-upgrades configuration
  template:
    src: unattended-upgrades.j2
    dest: "{{ common__unattended_upgrade_upgrades_file }}"
    owner: root
    group: root
    mode: 0644
