---
- name: restart ntp
  ansible.builtin.service:
    name: "{{ common__ntp_service[common__ntp_type] }}"
    state: restarted
- name: restart fail2ban
  ansible.builtin.service:
    name: "{{ common__f2b_servicename }}"
    state: restarted
...
